ALTER TABLE `user_vehicle` CHANGE `vehicle_pearlescentcolor` `vehicle_pearlescentcolor` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE `user_vehicle` CHANGE `vehicle_wheelcolor` `vehicle_wheelcolor` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_plateindex` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_neoncolor1` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_neoncolor2` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_neoncolor3` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_windowtint` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_wheeltype` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_mods0` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_mods1` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_mods2` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_mods3` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_mods4` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_mods5` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_mods6` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_mods7` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_mods8` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_mods9` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_mods10` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_mods11` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_mods12` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_mods13` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_mods14` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_mods15` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_mods16` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_turbo` varchar(255) NOT NULL DEFAULT 'off';
ALTER TABLE `user_vehicle` ADD `vehicle_tiresmoke` varchar(255) NOT NULL DEFAULT 'off';
ALTER TABLE `user_vehicle` ADD `vehicle_xenon` varchar(255) NOT NULL DEFAULT 'off';
ALTER TABLE `user_vehicle` ADD `vehicle_mods23` varchar(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_mods24` varchar(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_neon0` varchar(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_neon1` varchar(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_neon2` varchar(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_neon3` varchar(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_bulletproof` varchar(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_smokecolor1` varchar(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_smokecolor2` varchar(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_smokecolor3` varchar(255) DEFAULT NULL;
ALTER TABLE `user_vehicle` ADD `vehicle_modvariation` varchar(255) NOT NULL DEFAULT 'off';
